## Osnovne manipulacije tekstom

In [55]:
print ('hello Alex')

hello Alex


In [56]:
x = 3
print (x)

3


In [57]:
# Pokrenite ovu ćeliju nekoliko puta.
x = x + 5
# Output poslednje linije će biti prikazan.
x

8

In [58]:

my_string = "string može saržati karaktere koji uključuju i \n nove redove i \t tabove"
my_string

'string može saržati karaktere koji uključuju i \n nove redove i \t tabove'

In [59]:
print (my_string)

string može saržati karaktere koji uključuju i 
 nove redove i 	 tabove


In [60]:
#Isto važi i za output-e matematičkih operacija

12 + 45

57

In [61]:
#Isto važi i za output-e matematičkih operacija

24 * 3.5

84.0

## Liste (lists), rečnici (dictionaries)

In [62]:
x = [1, 2, 3]

In [63]:
# U python-u, numeracija počinje od 0
x[0], x[2]

(1, 3)

In [64]:
y = x[0:2] + [5, 10]
y

[1, 2, 5, 10]

In [65]:
y[::2]

[1, 5]

In [66]:
y[::-1]

[10, 5, 2, 1]

## Rečnici

In [67]:
d = {'a': 1, 'b': 2}

In [68]:
d['c'] = 3
d['casdsd'] = 34
d

{'a': 1, 'b': 2, 'c': 3, 'casdsd': 34}

In [69]:
for key, value in d.items():
    print (key, value)

a 1
b 2
c 3
casdsd 34


## Važne python biblioteke

 - numpy (numeričke operacije) + scipy (matematičke funkcije bitne za naučno programiranje)
 - matplotlib - grafičko prikazivanje rezultata
 - pandas - set operacija i fukncija za rad sa velikom količinom podataka (dataframe pristup nauci o podacima)
 - scikit-learn - biblioteke za mašinsko učenje

## Zdravo numpy!

`numpy` predstavlja jezgro tzv. naučnog python-a. Predstavlja najpristupačniji set alata za organizaciju numeričkih operacija u python-u.

In [70]:
import numpy

In [71]:
x = numpy.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
x.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [73]:
 x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [74]:
# slicing ima istu logiku kao i za liste, strings, tuples, numpy,...
x[:4]

array([0, 1, 2, 3])

In [75]:
print (x[:3])
print (x[3:7])
print (x[7:])

[0 1 2]
[3 4 5 6]
[7 8 9]


### Vektorske operacije

In [76]:
x = numpy.arange(10 ** 6) # Output predstavljaju jednako razmaknute vrednosti za dati interval
print(x)
# Vektorske operacije izvršavaju sličan zadatak za svaki element. U ovom slučaju, svaki element je pomnožena sa 3 i dodata mu je konstantna vrednost 12.
3 * x + 12.

[     0      1      2 ... 999997 999998 999999]


array([1.200000e+01, 1.500000e+01, 1.800000e+01, ..., 3.000003e+06,
       3.000006e+06, 3.000009e+06])

In [77]:
# Korišćenje operacije timeit zarad razumevanja da je ovakva računica izuzetno brza.
%timeit 3 * x + 12.

3.54 ms ± 471 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [78]:
Z = numpy.arange(15).reshape(5, 3)
Z

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [79]:
numpy.log(numpy.exp(Z)) # type conversion happened

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]])

In [80]:
Z += 4

In [81]:
Z

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [82]:
Z[::2, :]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

In [83]:
Z[[0, 2, 4], :]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

In [84]:
Z.sum(axis=1)

array([15, 24, 33, 42, 51])

In [85]:
# Numeracija osa takođe počinje od 0.
Z.sum(axis=0)

array([50, 55, 60])

In [86]:
Z.max(axis=1)

array([ 6,  9, 12, 15, 18])

In [87]:
Z2 = - Z
Z2 = numpy.sort(Z2, axis=1)
Z2

array([[ -6,  -5,  -4],
       [ -9,  -8,  -7],
       [-12, -11, -10],
       [-15, -14, -13],
       [-18, -17, -16]])

## Index-iranje sa boolean nizom

In [88]:
x = numpy.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [90]:
x[x < 7.4]

array([0, 1, 2, 3, 4, 5, 6, 7])

## Kopije

Mnogi operatori u numpy ne kreiraju kopije, već operišu sa istom memorijom

In [91]:
x = numpy.arange(10)
y = x[:5]

print (x, y)
y[0] = 10
print (x, y)

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4]
[10  1  2  3  4  5  6  7  8  9] [10  1  2  3  4]


**Output** je takav zato što se x i y vezuju za  __isto mesto u memoriji__.

In [92]:
x = numpy.arange(10)
y = x[:5].copy()
print (x, y)
y[0] = 10
print (x, y)

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9] [10  1  2  3  4]


## Random brojevi

Modul `numpy.random` pomaže sa generacijom random brojeva.

In [93]:
# Generisanje 10000 random brojeva
numpy.random.normal(loc=2, scale=12, size=10000)

array([-7.09396263e+00,  7.97693944e+00,  1.65237071e+01, ...,
        1.57446655e+01, -1.05468002e-02, -4.20164299e-01])

## Sortiranje

In [94]:
x = numpy.random.random(size=1000)
x = numpy.sort(x)

In [95]:
print (x[:10])
print (x[-10:])

[0.00025212 0.00075693 0.00362296 0.00497352 0.00568711 0.00584436
 0.00656797 0.00708847 0.00742264 0.00868005]
[0.98998772 0.99271075 0.99403544 0.99454977 0.99495859 0.99748596
 0.99868187 0.99881243 0.99902364 0.99958534]


## Arg...

arg-fukncije dozvoljavaju prisanje netrivijalnih operacija u samo nekoliko linija koda.

In [96]:
# random.random generiše uniformnu raspodelu u opsegu [0, 1]
random_numbers = numpy.random.random(size=1000)
indices = numpy.argsort(random_numbers) # Funkcija vraća indekse koji bi sortirali niz.

In [97]:
numpy.all(random_numbers[indices] == numpy.sort(random_numbers)) #Proverava da li korišćenje index-a u indices pravilno sortira niz random_numbers, numpy.all predstavlja logički AND svih elemenata niza boolean objekata - random_numbers[indices] == numpy.sort(random_numbers)

np.True_

In [98]:
indices[:10]

array([894, 167, 310, 138, 273, 586, 880,  76, 398, 364])

In [99]:
random_numbers.min(), random_numbers.max()

(np.float64(0.0019157385183038445), np.float64(0.9996969025730209))

In [100]:
random_numbers.argmax(), random_numbers[random_numbers.argmax()]

(np.int64(482), np.float64(0.9996969025730209))

In [101]:
random_numbers.argmin(), random_numbers[random_numbers.argmin()]

(np.int64(894), np.float64(0.0019157385183038445))

## Zadaci za vežbu

In [102]:
# 0. Importujte numpy


In [103]:
# 1. Sample-ujte 1000 elemeata koristeći normal distribution


In [104]:
# 2. Ostavite samo pozitivne brojeve (koristeći elemente iz zadatka 1.)


In [105]:
# 3. Prebrojte elemente koji su ostali kao output iz zadatka 2, odredite njihov minmum, maksimum, srednju vrednost i variance.

## Reference:
* `numpy` dokumentacija: https://docs.scipy.org/doc/numpy/reference/
    * Na (skoro) svako `numpy` pitanje je već odgovoreno na sajtu stackoverflow
* [From python to numpy: a beautiful book about numpy](https://github.com/rougier/from-python-to-numpy)
* Manipulacija podacima korišćenjem `numpy`: saveti i trikovi [part1](http://arogozhnikov.github.io/2015/09/29/NumpyTipsAndTricks1.html), [part2](http://arogozhnikov.github.io/2015/09/30/NumpyTipsAndTricks2.html)
